/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'dit' at '2016.11.05. 12:11' with Gradle 2.14.1
 *
 * @author dit, @date 2016.11.05. 12:11
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
